[[search-suggesters]]
== 建议器（Suggester）

搜索建议功能通过使用一个建议器对提供的文本给出建议的相近查询词条。搜索建议功能的部分特性还在开发当中。

搜索建议的请求体与 `_search` 请求中的查询请求体相邻。

NOTE: `_suggest` 端点已经过时，作为替代请通过 `_search` 端点使用搜索建议。在 5.0， `_search` 端点已经为仅作为搜索建议的搜索请求进行优化。

[source,js]
--------------------------------------------------
POST twitter/_search
{
  "query" : {
    "match": {
      "message": "tring out Elasticsearch"
    }
  },
  "suggest" : {
    "my-suggestion" : {
      "text" : "trying out Elasticsearch",
      "term" : {
        "field" : "message"
      }
    }
  }
}
--------------------------------------------------
// CONSOLE
// TEST[setup:twitter]

每个请求都可以指定多个搜索建议项（Suggestion）。每个建议项都可以通过指定一个任意名字来识别。在以下例子中请求了两个搜索建议项。`my-suggest-1` 和 `my-suggest-2` 均使用了 `term` 建议器但 `text` 的值却不同。

[source,js]
--------------------------------------------------
POST _search
{
  "suggest": {
    "my-suggest-1" : {
      "text" : "tring out Elasticsearch",
      "term" : {
        "field" : "message"
      }
    },
    "my-suggest-2" : {
      "text" : "kmichy",
      "term" : {
        "field" : "user"
      }
    }
  }
}
--------------------------------------------------
// CONSOLE
// TEST[setup:twitter]

在下方响应的例子中包含了 `my-suggest-1` 和 `my-suggest-2` 的建议项的响应。每个建议项部分包含多个入口。每个入口实际上是请求文本中的一个关键词以及包含该入口文本的建议项、建议结果文本中的原始的起始偏移量和长度以及是否命中了任何选项。

[source,js]
--------------------------------------------------
{
  "_shards": ...
  "hits": ...
  "took": 2,
  "timed_out": false,
  "suggest": {
    "my-suggest-1": [ {
      "text": "tring",
      "offset": 0,
      "length": 5,
      "options": [ {"text": "trying", "score": 0.8, "freq": 1 } ]
    }, {
      "text": "out",
      "offset": 6,
      "length": 3,
      "options": []
    }, {
      "text": "elasticsearch",
      "offset": 10,
      "length": 13,
      "options": []
    } ],
    "my-suggest-2": ...
  }
}
--------------------------------------------------
// TESTRESPONSE[s/"_shards": \.\.\./"_shards": "$body._shards",/]
// TESTRESPONSE[s/"hits": .../"hits": "$body.hits",/]
// TESTRESPONSE[s/"took": 2,/"took": "$body.took",/]
// TESTRESPONSE[s/"my-suggest-2": \.\.\./"my-suggest-2": "$body.suggest.my-suggest-2"/]


每个选项数组包含了一个选项对象，对象中包含了建议结果文本，它的文档频率以及对于该入口文本的分值。分值的意义取决于使用的建议器。term 建议器的分值基于编辑距离。

[float]
[[global-suggest]]
=== 全局的建议请求文本

为了避免重复给定搜索建议的请求文本，我们可以定义一个全局的文本。在下面的例子中定义了一个全局的请求文本并应用于请求 `my-suggest-1` 和 `my-suggest-2` 中。

[source,js]
--------------------------------------------------
POST _search
{
  "suggest": {
    "text" : "tring out Elasticsearch",
    "my-suggest-1" : {
      "term" : {
        "field" : "message"
      }
    },
    "my-suggest-2" : {
       "term" : {
        "field" : "user"
       }
    }
  }
}
--------------------------------------------------
// CONSOLE

上方例子中的请求文本还可以在搜索建议配置项中指定。在每个具体建议项中定义的文本会覆盖全局级别的请求文本。

include::suggesters/term-suggest.asciidoc[]

include::suggesters/phrase-suggest.asciidoc[]

include::suggesters/completion-suggest.asciidoc[]

include::suggesters/context-suggest.asciidoc[]

include::suggesters/misc.asciidoc[]
