[[pipeline]]
== 管道定义

管道是由一系列的<<ingest-processors, 处理器>>组成的，它们会被按照其定义顺序执行。一个管道有两个主要的字段组成： `description` 和一个 `processors` 列表：

[source,js]
--------------------------------------------------
{
  "description" : "...",
  "processors" : [ ... ]
}
--------------------------------------------------
// NOTCONSOLE

`description` 是一个特殊的字段，用于存储该管道的描述信息。

`processors` 参数定义了一个有序的处理器列表。

[[ingest-apis]]
== Ingest 接口

下面的 ingest 接口用于管理管道：

* <<put-pipeline-api>> 添加或更新管道
* <<get-pipeline-api>> 返回指定的管道
* <<delete-pipeline-api>> 删除一个管道
* <<simulate-pipeline-api>> 模拟一个管道调用

[[put-pipeline-api]]
=== 创建管道接口

创建管道接口添加或者更新一个集群中已存在的管道。

[source,js]
--------------------------------------------------
PUT _ingest/pipeline/my-pipeline-id
{
  "description" : "describe pipeline",
  "processors" : [
    {
      "set" : {
        "field": "foo",
        "value": "bar"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE

NOTE: 创建管道接口会通知所有 ingest 节点重新加载内存中管道，因此管道更新会立即生效。

[[get-pipeline-api]]
=== 获取管道接口

获取管道接口根据指定的 ID 返回对应的管道信息，这个接口始终返回一个管道的本地引用。

[source,js]
--------------------------------------------------
GET _ingest/pipeline/my-pipeline-id
--------------------------------------------------
// CONSOLE
// TEST[continued]

响应示例：

[source,js]
--------------------------------------------------
{
  "my-pipeline-id" : {
    "description" : "describe pipeline",
    "processors" : [
      {
        "set" : {
          "field" : "foo",
          "value" : "bar"
        }
      }
    ]
  }
}
--------------------------------------------------
// TESTRESPONSE

每个返回的管道都包含配置和版本信息。版本用于区分不同的管道，你可以指定多个 ID 同时返回多个管道，星号模糊匹配也是支持的。

[float]
[[versioning-pipelines]]
==== 指定管道版本

管道可以选择性的添加数值类型的版本号（ `version` 字段），这样便于外部系统更好的管理。 `version` 字段完全是可选的，且对外部管理系统来说是唯一的。如果想取消 `version` 字段的设定，可以简单的替换对应的管道而不指定该字段即可。

[source,js]
--------------------------------------------------
PUT _ingest/pipeline/my-pipeline-id
{
  "description" : "describe pipeline",
  "version" : 123,
  "processors" : [
    {
      "set" : {
        "field": "foo",
        "value": "bar"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE

为了检查指定的版本，可以<<common-options-response-filtering, 过滤响应内容>>，使用 `filter_path` 关键字限制响应的内容只返回指定的版本。

[source,js]
--------------------------------------------------
GET /_ingest/pipeline/my-pipeline-id?filter_path=*.version
--------------------------------------------------
// CONSOLE
// TEST[continued]

如下示例返回了一个简洁的响应内容，便于解析：

[source,js]
--------------------------------------------------
{
  "my-pipeline-id" : {
    "version" : 123
  }
}
--------------------------------------------------
// TESTRESPONSE

[[delete-pipeline-api]]
=== 删除管道接口

删除管道接口指定 ID 删除对应的管道，可以使用通配符（ `my-*`, `*` ）。

[source,js]
--------------------------------------------------
DELETE _ingest/pipeline/my-pipeline-id
--------------------------------------------------
// CONSOLE
// TEST[continued]

////
Hidden setup for wildcard test:
[source,js]
--------------------------------------------------
PUT _ingest/pipeline/wild-one
{
  "description" : "first pipeline to be wildcard deleted",
  "processors" : [ ]
}

PUT _ingest/pipeline/wild-two
{
  "description" : "second pipeline to be wildcard deleted",
  "processors" : [ ]
}

DELETE _ingest/pipeline/*
--------------------------------------------------
// CONSOLE

Hidden expected response:
[source,js]
--------------------------------------------------
{
"acknowledged": true
}
--------------------------------------------------
// TESTRESPONSE
////

[[simulate-pipeline-api]]
=== 模拟管道接口

模拟管道接口执行一个指定的管道并在请求体中携带一个文档的集合。

模拟时，你可以指定一个已存在的管道或者在请求体重定义一个新的管道。

如下是一个在请求体中指定新的管道内容模拟管道的示例请求：

[source,js]
--------------------------------------------------
POST _ingest/pipeline/_simulate
{
  "pipeline" : {
    // pipeline definition here
  },
  "docs" : [
    { "_source": {/** first document **/} },
    { "_source": {/** second document **/} },
    // ...
  ]
}
--------------------------------------------------
// NOTCONSOLE

如下是一个模拟已存在管道的请求结构：

[source,js]
--------------------------------------------------
POST _ingest/pipeline/my-pipeline-id/_simulate
{
  "docs" : [
    { "_source": {/** first document **/} },
    { "_source": {/** second document **/} },
    // ...
  ]
}
--------------------------------------------------
// NOTCONSOLE

如下是一个模拟自定义管道请求的响应内容：

[source,js]
--------------------------------------------------
POST _ingest/pipeline/_simulate
{
  "pipeline" :
  {
    "description": "_description",
    "processors": [
      {
        "set" : {
          "field" : "field2",
          "value" : "_value"
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "foo": "bar"
      }
    },
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "foo": "rab"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE

响应内容：

[source,js]
--------------------------------------------------
{
   "docs": [
      {
         "doc": {
            "_id": "id",
            "_index": "index",
            "_type": "_doc",
            "_source": {
               "field2": "_value",
               "foo": "bar"
            },
            "_ingest": {
               "timestamp": "2017-05-04T22:30:03.187Z"
            }
         }
      },
      {
         "doc": {
            "_id": "id",
            "_index": "index",
            "_type": "_doc",
            "_source": {
               "field2": "_value",
               "foo": "rab"
            },
            "_ingest": {
               "timestamp": "2017-05-04T22:30:03.188Z"
            }
         }
      }
   ]
}
--------------------------------------------------
// TESTRESPONSE[s/"2017-05-04T22:30:03.187Z"/$body.docs.0.doc._ingest.timestamp/]
// TESTRESPONSE[s/"2017-05-04T22:30:03.188Z"/$body.docs.1.doc._ingest.timestamp/]

[[ingest-verbose-param]]
==== 查看详细的结果
你可以利用模拟管道接口查看每个处理器是如何处理每个流过的文档的。如果想查看每个处理器的中间结果，可以在请求中添加 `verbose` 参数。 如下是一个携带 `verbose` 参数的请求，返回详细信息的例子：

[source,js]
--------------------------------------------------
POST _ingest/pipeline/_simulate?verbose
{
  "pipeline" :
  {
    "description": "_description",
    "processors": [
      {
        "set" : {
          "field" : "field2",
          "value" : "_value2"
        }
      },
      {
        "set" : {
          "field" : "field3",
          "value" : "_value3"
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "foo": "bar"
      }
    },
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "foo": "rab"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE

响应内容：

[source,js]
--------------------------------------------------
{
   "docs": [
      {
         "processor_results": [
            {
               "doc": {
                  "_id": "id",
                  "_index": "index",
                  "_type": "_doc",
                  "_source": {
                     "field2": "_value2",
                     "foo": "bar"
                  },
                  "_ingest": {
                     "timestamp": "2017-05-04T22:46:09.674Z"
                  }
               }
            },
            {
               "doc": {
                  "_id": "id",
                  "_index": "index",
                  "_type": "_doc",
                  "_source": {
                     "field3": "_value3",
                     "field2": "_value2",
                     "foo": "bar"
                  },
                  "_ingest": {
                     "timestamp": "2017-05-04T22:46:09.675Z"
                  }
               }
            }
         ]
      },
      {
         "processor_results": [
            {
               "doc": {
                  "_id": "id",
                  "_index": "index",
                  "_type": "_doc",
                  "_source": {
                     "field2": "_value2",
                     "foo": "rab"
                  },
                  "_ingest": {
                     "timestamp": "2017-05-04T22:46:09.676Z"
                  }
               }
            },
            {
               "doc": {
                  "_id": "id",
                  "_index": "index",
                  "_type": "_doc",
                  "_source": {
                     "field3": "_value3",
                     "field2": "_value2",
                     "foo": "rab"
                  },
                  "_ingest": {
                     "timestamp": "2017-05-04T22:46:09.677Z"
                  }
               }
            }
         ]
      }
   ]
}
--------------------------------------------------
// TESTRESPONSE[s/"2017-05-04T22:46:09.674Z"/$body.docs.0.processor_results.0.doc._ingest.timestamp/]
// TESTRESPONSE[s/"2017-05-04T22:46:09.675Z"/$body.docs.0.processor_results.1.doc._ingest.timestamp/]
// TESTRESPONSE[s/"2017-05-04T22:46:09.676Z"/$body.docs.1.processor_results.0.doc._ingest.timestamp/]
// TESTRESPONSE[s/"2017-05-04T22:46:09.677Z"/$body.docs.1.processor_results.1.doc._ingest.timestamp/]

[[accessing-data-in-pipelines]]
== 访问管道中的数据
管道中的处理器可以读写流过管道的文档，处理器可以访问文档中具体的字段，以及文档的元数据。

[float]
[[accessing-source-fields]]
=== 访问字段原始值
从 source 中访问字段原始值非常简单，你可以简单的指定字段的名称即可。例如：

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "my_field",
    "value": 582.1
  }
}
--------------------------------------------------
// NOTCONSOLE

上面的例子中，也可以直接加上 `_source` 前缀关键字进行访问，例如：

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "_source.my_field",
    "value": 582.1
  }
}
--------------------------------------------------
// NOTCONSOLE

[float]
[[accessing-metadata-fields]]
=== 访问元数据字段
你可以采用同样的方法访问元数据字段，因为 Elasticsearch 不允许用户定义的字段和元数据字段重复。如下的例子将文档元数据中的 `_id` 字段的值设置为 `1` ：

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "_id",
    "value": "1"
  }
}
--------------------------------------------------
// NOTCONSOLE

这些元数据字段都可以被处理器直接访问：`_index`, `_type`, `_id`, `_routing`.

[float]
[[accessing-ingest-metadata]]
=== 访问 Ingest 元数据字段
除了原始字段和 source 中用户定义的字段，ingest 功能在文档中还添加了 ingest 元数据，这些元数据属性可以通过 `_ingest` 关键字来访问。目前，在 `_ingest.timestamp` 键下面添加了 ingest 时间戳作为元数据。这里的 ingest 时间戳是指当 Elasticsearch 收到一个写入（index 或者 bulk）请求后，开始处理文档的时间。

任何一个处理器在处理文档的时候都可以添加 ingest 相关的元数据。Ingest 元数据是临时的，当文档被管道处理完毕之后就丢失了。因此，ingest 元数据不会被索引保存。

如下的示例添加了一个名为 `received` 的字段，值是 ingest 时间戳：

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "received",
    "value": "{{_ingest.timestamp}}"
  }
}
--------------------------------------------------
// NOTCONSOLE

不像 Elasticsearch 元数据字段，ingest 元数据字段名称 `_ingest` 关键字在文档中是可以成为一个自定义字段的。需要使用 `_source._ingest` 来访问文档中定义的字段，否则 `_ingest` 关键字将会被解析成 ingest 元数据字段。

[float]
[[accessing-template-fields]]
=== 访问模板中的字段及元数据字段
许多处理器设置支持模板，支持模板的设定可以有零个或多个模板片段。一个模板片段从 `{{` 开始，到 `}}` 结束。访问模板中的字段及元数据字段（metafields）和处理正常字段的设置是一样的。

如下示例添加一个名为 `field_c` 的字段，它的值由 `field_a` 和 `field_b` 两个字段的值拼接而成。

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "field_c",
    "value": "{{field_a}} {{field_b}}"
  }
}
--------------------------------------------------
// NOTCONSOLE

如下示例使用 source 中 `geoip.country_iso_code` 字段的值来设置 `_index` 值，这样文档就会被保存到这个索引中：

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "_index",
    "value": "{{geoip.country_iso_code}}"
  }
}
--------------------------------------------------
// NOTCONSOLE

动态字段名称原始支持的，如下示例设置 `service` 字段的值为 `code` 字段的值：

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "{{service}}",
    "value": "{{code}}"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[handling-failure-in-pipelines]]
== 处理管道中的错误

在常用的场景中，当一个管道定义了一个包含多个处理器的列表，它们将被顺序执行，当处理到第一个异常的时候，管道会因异常而终止。例如，可能有日志内容不匹配指定的 `grok` 表达式。除了抛出异常终止执行，你可能需要将该出错的文档写到另外一个索引中。

如果想打开上述异常处理的功能，你可以使用 `on_failure` 参数。 `on_failure` 参数定义了一个处理器列表，这些处理器将在正常处理文档抛出异常时被执行。你可以在管道层面指定这个参数，或者在处理器层面指定。如果处理器指定了 `on_failure` 配置，无论指定的内容是否为空，处理器抛出的所有异常将被捕获。管道将继续执行剩下的处理器。你可以使用嵌套机制在 `on_failure` 参数中定义更多的嵌套处理器。

下面的示例定义了一个管道，将被处理文档中的 `foo` 字段改名为 `bar`. 如果这个文档中不包含 `foo` 字段，这个处理器将会附加一个错误信息到文档里便于后面在 Elasticsearch 中进行分析。

[source,js]
--------------------------------------------------
{
  "description" : "my first pipeline with handled exceptions",
  "processors" : [
    {
      "rename" : {
        "field" : "foo",
        "target_field" : "bar",
        "on_failure" : [
          {
            "set" : {
              "field" : "error",
              "value" : "field \"foo\" does not exist, cannot rename to \"bar\""
            }
          }
        ]
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

下面的示例在整个管道层面定义了一个 `on_failure` 参数块，用于将处理错误的文档保存到对应的索引中。

[source,js]
--------------------------------------------------
{
  "description" : "my first pipeline with handled exceptions",
  "processors" : [ ... ],
  "on_failure" : [
    {
      "set" : {
        "field" : "_index",
        "value" : "failed-{{ _index }}"
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

除了在处理器中定义各种异常处理，也可以通过指定 `ignore_failure` 参数直接忽略异常而继续执行下一个处理器

在如下的示例中，如果 `foo` 字段不存在异常被捕获，管道将继续执行，也就是说在这种情况下管道不会对异常做任何处理。 

[source,js]
--------------------------------------------------
{
  "description" : "my first pipeline with handled exceptions",
  "processors" : [
    {
      "rename" : {
        "field" : "foo",
        "target_field" : "bar",
        "ignore_failure" : true
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

任何处理器中都可以设置 `ignore_failure` 参数，默认为 `false`.

[float]
[[accessing-error-metadata]]
=== 访问元数据字段错误信息处理异常

如果想访问失败的处理器的详细错误信息，只需要访问这些元数据字段 `on_failure_message`, `on_failure_processor_type` 和 `on_failure_processor_tag` 即可。这些字段只能在 `on_failure` 包括的区域中访问。

如下是一个之前看过的例子的升级版。通过使用 `on_failure_message` 元数据字段提供错误信息，这样无需再手动设置错误信息：

[source,js]
--------------------------------------------------
{
  "description" : "my first pipeline with handled exceptions",
  "processors" : [
    {
      "rename" : {
        "field" : "foo",
        "to" : "bar",
        "on_failure" : [
          {
            "set" : {
              "field" : "error",
              "value" : "{{ _ingest.on_failure_message }}"
            }
          }
        ]
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

[[ingest-processors]]
== 处理器

所有的处理器都被定义在如下所示的管道定义区：

[source,js]
--------------------------------------------------
{
  "PROCESSOR_NAME" : {
    ... processor configuration options ...
  }
}
--------------------------------------------------
// NOTCONSOLE

每个处理器定义了自己的配置参数，但是所有的处理器都可以定义 `tag`, `on_failure` 和 `if` 字段，这些字段是可选的。
Each processor defines its own configuration parameters, but all processors have
the ability to declare `tag`, `on_failure` and `if` fields. These fields are optional.

`tag` 字段是一个简单的字符串标识符，其用于标识管道中一个具体的处理器实例。 `tag` 字段不影响处理器的行为，但是跟踪具体处理器的错误信息的时候非常有用，可用于识别不同的处理器。

`if` 字段必须包含一个可以返回 boolean 值的脚本。如果这个脚本返回 `true` ，处理器将会被执行并处理提供的文档，否则该处理器将会被跳过。
`if` 字段在 <<script-processor, script-options>> 中定义的脚本字段中接受一个对象，该对象可以以只读形式访问文档，访问方式和在 <<script-processor>> 中定义在脚本中访问 `ctx` 变量一样。

[source,js]
--------------------------------------------------
{
  "set": {
    "if": "ctx.bar == 'expectedValue'",
    "field": "foo",
    "value": "bar"
  }
}
--------------------------------------------------
// NOTCONSOLE

查看 <<handling-failure-in-pipelines>> 了解更多关于 `on_failure` 字段及管道中错误处理的内容。

<<ingest-info, 节点信息接口>>会提供每个节点所有可用的处理器。

自定义的处理器必须在每个节点上安装。如果管道中定义的某个处理器并不是每个节点都有，则创建管道接口将会失败。如果你依赖一个自定义的处理器插件，请通过在 `config/elasticsearch.yml` 配置文件中定义 `plugin.mandatory` 确保这些插件是强制的。例如：

[source,yaml]
--------------------------------------------------
plugin.mandatory: ingest-attachment,ingest-geoip
--------------------------------------------------

这样节点将不会被成功启动如果其中一个插件不可用。

<<ingest-info, 节点信息接口>>可以用来获取 ingest 使用统计信息，全局的和每个管道的。可以非常方便的查看哪个管道使用的最频繁，或者处理过程中最花时间。

[float]
=== Ingest 处理器插件

更多的 ingest 处理器可以通过自定义 Elasticsearch {plugins}/intro.html[插件]实现。查看 {plugins}/ingest.html[Ingest 插件]获取更多可用的 ingest 插件。

[[append-processor]]
=== 追加处理器
追加一个或多个值到一个已存在的数组字段中，如果字段已存在且是一个数组。转换一个标量为一个数组并追加一个或多个值，如果字段存在且是一个标量。创建一个数组字段包含所提供的值，如果字段不存在。接受单个值或者一组值。

[[append-options]]
.Append Options
[options="header"]
|======
| 名称     | 必选      | 默认值   | 描述
| `field`  | 是       | -        | 被追加的字段。支持<<accessing-template-fields, 模板片段>>。
| `value`  | 是       | -        | 被追加的值。支持<<accessing-template-fields, 模板片段>>。
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "append": {
    "field": "tags",
    "value": ["production", "{{app}}", "{{owner}}"]
  }
}
--------------------------------------------------
// NOTCONSOLE

[[bytes-processor]]
=== 字节处理器
将一个可读的字节值（例如：1kb）转换为其真实值（例如：1024）。

支持的单位包括，"b"、"kb"、"mb"、"gb"、"tb"、"pb" 且不区分大小写。如果字段的后缀格式不支持或者计算结果超过 2^63 则会报错。

[[bytes-options]]
.字节处理器选项
[options="header"]
|======
| 名称             | 必选      | 默认值   | 描述
| `field`          | 是        | -        | 被转换的字段。
| `target_field`   | 否        | `field`  | 目标字段，默认情况字段会被就地更新。
| `ignore_missing` | 否        | `false`  | 如果为 `true` 且 `field` 不存在或者为 `null`, 处理器不会对文档做出任何修改直接退出。
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "bytes": {
    "field": "file.size"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[convert-processor]]
=== 转换处理器
将当前文档中的某个字段转换成另外一种类型。例如将字符串类型转换为整型。如果字段是一个数组，所有的成员将会被转换。

支持的类型包括： `integer` 、 `long` 、 `float` 、 `double` 、 `string` 、 `boolean` 和 `auto` 。

字符串转换为 `boolean` 场景，如果字符串值等于 `true` （不区分大小写）则为 true，如果字符串值等于 `false` （不区分大小写）则为 false。否则会抛出异常。

指定 `auto` ，将会尝试将字符串字段值转换为相关的非字符串类型。例如，一个字符串字段其值为 `"true"` 将会被转换为一个 boolean 类型且值为 `true` 。注意，在 `auto` 场景下，float 类型优先级高于 double。例如， `"242.15"` 将会被自动的转换为 `float` 类型的 `242.15` 。如果提供的一个字段不能被正确的转换，转换处理器将仍然处理成功并保留字段原始值。在这种情况下， `target_field` 将仍然被更新为未转换的字段值。

[[convert-options]]
.Convert Options
[options="header"]
|======
| 名称             | 必须      | 默认值   | 描述
| `field`          | 是        | -        | 值被转换的字段。
| `target_field`   | 否        | `field`  | 值被转换后保存的目标字段，默认情况字段被就地更新。
| `type`           | 是        | -        | 值被转换的类型。
| `ignore_missing` | 否        | `false`  | 如果为 `true` 且 `field` 不存在或者为 `null`, 处理器将会退出不对文档做任何修改。
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
PUT _ingest/pipeline/my-pipeline-id
{
  "description": "converts the content of the id field to an integer",
  "processors" : [
    {
      "convert" : {
        "field" : "id",
        "type": "integer"
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

[[date-processor]]
=== 日期处理器

解析字段中的日期字段，并使用该日期或者时间戳作为文档的时间（timestamp）字段。默认情况，日期处理器添加解析过的日期值作为一个新的字段并命名为 `@timestamp` ，你也可以通过 `target_field` 参数配置一个不同的名称。日期处理器支持多种类型的日期格式，它们在处理器定义的时候指定。它们将会被按照其定义的顺序来解析目标日期字段。

[[date-options]]
.日期选项
[options="header"]
|======
| 名称                   | 必须      | 默认值              | 描述
| `field`                | 是        | -                   | 获取日期的字段。
| `target_field`         | 否        | @timestamp          | 日期目标保存字段。
| `formats`              | 是        | -                   | 日期格式的数组，可以是 Joda 模式的，也可以是如下几种格式的一种：ISO8601、UNIX、UNIX_MS 或者 TAI64N。
| `timezone`             | 否        | UTC                 | 解析日期时使用的时区。支持<<accessing-template-fields, 模板片段>>。
| `locale`               | 否        | ENGLISH             | 解析日期时使用的语言环境（locale），在解析月份名称或星期时使用。支持<<accessing-template-fields, 模板片段>>。
include::ingest-node-common-processor.asciidoc[]
|======

如下是解析 `initial_date` 字段日期值并添加至 `timestamp` 字段的例子：

[source,js]
--------------------------------------------------
{
  "description" : "...",
  "processors" : [
    {
      "date" : {
        "field" : "initial_date",
        "target_field" : "timestamp",
        "formats" : ["dd/MM/yyyy hh:mm:ss"],
        "timezone" : "Europe/Amsterdam"
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

`timezone` 和 `locale` 处理器参数是模板化的，这意味着它们的值可以从文档的字段中提取。如下的例子演示如何从文档中已存在的字段 `my_timezone` 和 `my_locale` 中提取语言环境和时区（locale/timezone）信息：

[source,js]
--------------------------------------------------
{
  "description" : "...",
  "processors" : [
    {
      "date" : {
        "field" : "initial_date",
        "target_field" : "timestamp",
        "formats" : ["ISO8601"],
        "timezone" : "{{my_timezone}}",
        "locale" : "{{my_locale}}"
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

[[date-index-name-processor]]
=== 日期索引名称处理器

这个处理器的目的是让写入的文档被正确的按照其时间字段指定的时间放入对应的时间序列索引中。主要是基于<<date-math-index-names, 日期计算索引名称表达式>>的支持。

这个处理器通过基于指定的索引名称前缀加上计算出来的时间后缀作为索引名称来设定 `_index` 元数据字段，文档中的日期或时间戳字段将会用于计算时间后缀。 

首先，这个处理器从文档某个字段中提取日期或时间戳并处理，字段的值被解析成什么格式的日期是可以配置的。接下来，指定的索引名称前缀将和处理好的日期被格式化成完整的滚动索引名称，在格式化成索引名过程中，格式是可配置的。

如下是通过一个管道将文档写入到按月滚动的索引中的例子，该索引名以 `myindex-` 为前缀，后缀从 `date1` 字段中解析。

[source,js]
--------------------------------------------------
PUT _ingest/pipeline/monthlyindex
{
  "description": "monthly date-time index naming",
  "processors" : [
    {
      "date_index_name" : {
        "field" : "date1",
        "index_name_prefix" : "myindex-",
        "date_rounding" : "M"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE

使用这个管道处理写入请求：

[source,js]
--------------------------------------------------
PUT /myindex/_doc/1?pipeline=monthlyindex
{
  "date1" : "2016-04-25T12:02:01.789Z"
}
--------------------------------------------------
// CONSOLE
// TEST[continued]

[source,js]
--------------------------------------------------
{
  "_index" : "myindex-2016-04-01",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
--------------------------------------------------
// TESTRESPONSE

上面的请求不会将示例文档写入名为 `myindex` 的索引中，而是写入 `myindex-2016-04-01` 索引中，因为其是按月分类滚动的。这是因为日期索引名称处理器覆盖了文档的 `_index` 属性。

我们可以通过管道模拟请求接口查看实际写入请求中，文档如何根据其提供的日期字段分配索引：

[source,js]
--------------------------------------------------
POST _ingest/pipeline/_simulate
{
  "pipeline" :
  {
    "description": "monthly date-time index naming",
    "processors" : [
      {
        "date_index_name" : {
          "field" : "date1",
          "index_name_prefix" : "myindex-",
          "date_rounding" : "M"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "date1": "2016-04-25T12:02:01.789Z"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE

结果：

[source,js]
--------------------------------------------------
{
  "docs" : [
    {
      "doc" : {
        "_id" : "_id",
        "_index" : "<myindex-{2016-04-25||/M{yyyy-MM-dd|UTC}}>",
        "_type" : "_type",
        "_source" : {
          "date1" : "2016-04-25T12:02:01.789Z"
        },
        "_ingest" : {
          "timestamp" : "2016-11-08T19:43:03.850+0000"
        }
      }
    }
  ]
}
--------------------------------------------------
// TESTRESPONSE[s/2016-11-08T19:43:03.850\+0000/$body.docs.0.doc._ingest.timestamp/]

上面的示例展示了 `_index` 被修改为 `<myindex-{2016-04-25||/M{yyyy-MM-dd|UTC}}>` 。按照在<<date-math-index-names, 日期计算索引名称文档>>中描述的方法，Elasticsearch 会认为其是 `2016-04-01` （当月第一天）。

[[date-index-name-options]]
.日期索引名称选项
[options="header"]
|======
| 名称                   | 必选      | 默认值                       | 描述
| `field`                | 是        | -                            | 获取日期或时间戳的字段。
| `index_name_prefix`    | 否        | -                            | 日期前面的索引名前缀，支持<<accessing-template-fields, 模板片段>>.
| `date_rounding`        | 是        | -                            | 格式化索引名的时候如何规整日期。合法的值包括： `y` (年), `M` (月), `w` (周), `d` (日), `h` (小时), `m` (分) and `s` (秒)。支持<<accessing-template-fields, 模板片段>>。
| `date_formats`         | 否        | yyyy-MM-dd'T'HH:mm:ss.SSSZ   | 一组日期格式，用于解析被处理文档中的日期/时间戳。可以是 Joda 模式或者以下格式中的一种：ISO8601、UNIX、UNIX_MS 或者 TAI64N。
| `timezone`             | 否        | UTC                          | 解析日期时用的时区，当日期计算索引名称支持时，用于产生具体的索引名称。
| `locale`               | 否        | ENGLISH                      | 解析预处理文档中的日期时使用的语言环境设置，在解析月份名称或星期时使用。 
| `index_name_format`    | 否        | yyyy-MM-dd                   | 指定索引名称中的日期格式，支持合法的 Joda 模式。支持<<accessing-template-fields, 模板片段>>。
include::ingest-node-common-processor.asciidoc[]
|======

[[dissect-processor]]
=== 剖析解析器

和 <<grok-processor,Grok 处理器>>类似，剖析（dissect）处理器也是从文档字段的文本信息里面提取结构化数据。与 <<grok-processor,Grok 处理器>>不同的是，剖析处理器不使用https://en.wikipedia.org/wiki/Regular_expression[正则表达式]。这样使它的语法变得简单，在某些场景下比 <<grok-processor,Grok 处理器>>速度快。

剖析处理器基于定义好的模式（pattern）匹配单一的文本字段。

例如以下的模式：
[source,txt]
--------------------------------------------------
%{clientip} %{ident} %{auth} [%{@timestamp}] \"%{verb} %{request} HTTP/%{httpversion}\" %{status} %{size}
--------------------------------------------------
将会匹配如下格式的一行日志：
[source,txt]
--------------------------------------------------
1.2.3.4 - - [30/Apr/1998:22:00:52 +0000] \"GET /english/venues/cities/images/montpellier/18.gif HTTP/1.0\" 200 3171
--------------------------------------------------
产生如下字段的一条文档数据：
[source,js]
--------------------------------------------------
"doc": {
  "_index": "_index",
  "_type": "_type",
  "_id": "_id",
  "_source": {
    "request": "/english/venues/cities/images/montpellier/18.gif",
    "auth": "-",
    "ident": "-",
    "verb": "GET",
    "@timestamp": "30/Apr/1998:22:00:52 +0000",
    "size": "3171",
    "clientip": "1.2.3.4",
    "httpversion": "1.0",
    "status": "200"
  }
}
--------------------------------------------------
// NOTCONSOLE

剖析模式会按照被丢弃的内容进行切分匹配，在上面的示例中，第一个被丢弃的内容就是空格，因为模式中字段之间是直接用空格分开的。剖析模式查找空格，然后将空格之前的所有内容赋值给 `clientip` 字段。后面的匹配中，当匹配 `[` 和 `]` 后，会把它们之间的所有内容赋值给 `@timestamp` 字段。注意正确的定义这些被丢弃的字符串片段才能构建出正确的剖析模式。 

成功的匹配需要在模式中定义的所有键都有对应的值。如果任何一个 `%{keyname}` 定义的模式没有对应的值，就会抛出一个异常，可能会直接被当作<<handling-failure-in-pipelines,on_falure>>处理。一个空键 `%{}` 或者一个<<dissect-modifier-named-skip-key, 命名为跳过的键>>也可以用来匹配值，这样会去掉文档中的值。所有被匹配的值将会被处理成字符串类型。<<convert-processor, 转换处理器>>可以用于转换数据类型。

剖析处理器也支持<<dissect-key-modifiers, 键修改>>，这样可以改变剖析处理器默认的行为。例如，你可以让剖析处理器忽略指定的字段、添加字段、跳过填充值等等。详细查看<<dissect-key-modifiers, 这里>>获取更多信息。

[[dissect-options]]
.剖析模式选项
[options="header"]
|======
| 名称              | 必须      | 默认值   | 描述
| `field`           | 是        | -        | 被剖析的字段
| `pattern`         | 是        | -        | 剖析使用的匹配模式
| `append_separator`| 否        | "" (空字符串) | 对追加字段的分割符
| `ignore_missing`  | 否        | false         | 如果为 `true` 且 `field` 指定的字段不存在或者是 `null`, 处理器将会跳过文档不做任何处理
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "dissect": {
    "field": "message",
    "pattern" : "%{clientip} %{ident} %{auth} [%{@timestamp}] \"%{verb} %{request} HTTP/%{httpversion}\" %{status} %{size}"
   }
}
--------------------------------------------------
// NOTCONSOLE
[[dissect-key-modifiers]]
==== 剖析处理器键修改器
键修改器可以修改剖析处理器的默认行为。键修改器可能在 `%{keyname}` 的左边或者右边出现，但一定在 `%{` 和 `}` 之间。例如 `%{+keyname ->}` 有追加和右填充修改器。 

.剖析处理器键修改器选项
[options="header"]
|======
| 编辑器      | 名称               | 位置       | 示例                      | 描述                                                  | 详情
| `->`          | 跳过右填充         | 右边最大匹配   | `%{keyname1->}`  | 跳过右边所有重复的字符                                    | <<dissect-modifier-skip-right-padding,link>>
| `+`           | 追加               | 左边           | `%{+keyname} %{+keyname}`    | 追加两个或更多的字段在一起                    | <<dissect-modifier-append-key,link>>
| `+` 携带 `/n` | 按顺序追加         | 左边和右边     | `%{+keyname/2} %{+keyname/1}` | 按照指定的顺序追加两个或跟多的字段在一起     | <<dissect-modifier-append-key-with-order,link>>
| `?`           | 命名的跳过键       | 左边           | `%{?ignoreme}`  | 在输出结果中跳过匹配的值。和 `%{}` 的行为相同| <<dissect-modifier-named-skip-key,link>>
| `*` 和 `&`    | 引用键             | 左边                    | `%{*r1} %{&r1}`    | 将输出的键设置为 `*` 值设置为 `&`  | <<dissect-modifier-reference-keys,link>>
|======

[[dissect-modifier-skip-right-padding]]
===== 右填充修改器 (`->`)

这个算法在剖析过程中非常严格，要求所有的字符都必须匹配目标字符串。例如，这个模式 `%{fookey} %{barkey}` （1个空格），将会匹配这个字符串 "foo{nbsp}bar"（1个空格）， 但是不匹配这个字符串 "foo{nbsp}{nbsp}bar"（两个空格），因为指定的模式只有一个空格而目标字符串有两个。

这个右填充修改器在上述场景下可以派上用场，这个模式 `%{fookey->} %{barkey}` 中添加了右填充修改器，现在将会匹配 "foo{nbsp}bar"（1个空格）和 "foo{nbsp}{nbsp}bar"（两个空格），甚至是多个空格 "foo{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}bar"（10个空格）场景。

使用右填充修改器处理关键字 `%{keyname->}` 之后的所有重复字符。

右填充修改器可以任意的键或者其它修改器一起使用，它应该始终是一个最右边的修改器。例如，`%{+keyname/1->}` and `%{->}` 。

右填充修改器示例：
|======
| *Pattern* | `%{ts->} %{level}`
| *Input*   |  1998-08-10T17:15:42,466{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}WARN
| *Result*  a|
* ts = 1998-08-10T17:15:42,466
* level = WARN
|======

右填充修改器也可以和一个空键一起使用来跳过不需要的数据。例如，相同的输入字符串，但是用括号括起来，需要使用一个空的右填充键来实现相同的结果。

如下示例演示用右填充修改器跳过中间的多个空格：
|======
| *Pattern* | `[%{ts}]%{->}[%{level}]`
| *Input*   | [1998-08-10T17:15:42,466]{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}[WARN]
| *Result*  a|
* ts = 1998-08-10T17:15:42,466
* level = WARN
|======

===== 追加修改器 (`+`)
[[dissect-modifier-append-key]]
剖析处理器支持在输出结果中追加两个或多个结果。值是从左到右追加，可以为追加的数据指定一个分割符。

如下的示例中追加分割符定义为一个空格：
|======
| *Pattern* | `%{+name} %{+name} %{+name} %{+name}`
| *Input*   | john jacob jingleheimer schmidt
| *Result*  a|
* name = john jacob jingleheimer schmidt
|======

===== 按顺序追加修改器 (`+` 加 `/n`)
[[dissect-modifier-append-key-with-order]]
剖析处理器支持拼接两个或更多的结果到输出中。值按照 `/n` 里面定义的顺序追加。同样可以指定一个分割符。

如下示例演示了使用逗号作为分隔符的按顺序追加的修改器：
|======
| *Pattern* | `%{+name/2} %{+name/4} %{+name/3} %{+name/1}`
| *Input*   | john jacob jingleheimer schmidt
| *Result*  a|
* name = schmidt,john,jingleheimer,jacob
|======

===== 命名跳过键 (`?`)
[[dissect-modifier-named-skip-key]]
剖析处理器支持在最终结果集中忽略一些数据匹配，这个可以通过指定空键 `%{}` 来实现。但是为了可读性，需要给空键一个命名。 

命名跳过键示例：
|======
| *Pattern* | `%{clientip} %{?ident} %{?auth} [%{@timestamp}]`
| *Input*   | 1.2.3.4 - - [30/Apr/1998:22:00:52 +0000]
| *Result*  a|
* ip = 1.2.3.4
* @timestamp = 30/Apr/1998:22:00:52 +0000
|======

===== 引用键 (`*` 和 `&`)
[[dissect-modifier-reference-keys]]
剖析处理器支持使用解析过的值作为结构化数据的键值对。假设一个系统中有部分键值对的数据，引用键可以帮助保留它们的键值关系。
 
引用键修改器示例：
|======
| *Pattern* | `[%{ts}] [%{level}] %{*p1}:%{&p1} %{*p2}:%{&p2}`
| *Input*   | [2018-08-10T17:15:42,466] [ERR] ip:1.2.3.4 error:REFUSED
| *Result*  a|
* ts = 1998-08-10T17:15:42,466
* level = ERR
* ip = 1.2.3.4
* error = REFUSED
|====== 

[[drop-processor]]
=== 丢弃处理器
丢弃文档且不抛出任何异常。这个处理器可以在带条件的场景有效的过滤文档。

[[drop-options]]
.丢弃处理器选项
[options="header"]
|======
| 名称             | 必须  | 默认值  | 描述
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "drop": {
    "if" : "ctx.network_name == 'Guest'"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[dot-expand-processor]]
=== 点扩展处理器

使用点号扩展一个字段为一个对象字段。这个处理器允许名称中包含点号的字段可以被管道中的其它处理器访问。不使用这个处理器，这些<<accessing-data-in-pipelines,字段>>不能被其它处理器访问。

[[dot-expender-options]]
.点扩展处理器选项
[options="header"]
|======
| 名称     | 必须      | 默认值   | 描述
| `field`  | 是        | -        | 被扩展的字段。
| `path`   | 否        | -        | The field that contains the field to expand. 仅当被扩展的字段是对象字段的一部分的时候猜啊需要，因为 `field` 选项只能识别最底层的叶子字段。Only required if the field to expand is part another object field, because the `field` option can only understand leaf fields.
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "dot_expander": {
    "field": "foo.bar"
  }
}
--------------------------------------------------
// NOTCONSOLE

例如如下的点扩展处理器可以将如下文档：

[source,js]
--------------------------------------------------
{
  "foo.bar" : "value"
}
--------------------------------------------------
// NOTCONSOLE

处理为：

[source,js]
--------------------------------------------------
{
  "foo" : {
    "bar" : "value"
  }
}
--------------------------------------------------
// NOTCONSOLE

如果 `foo` 已经嵌套了一个 `bar` 字段，这个处理器会将其与 `foo.bar` 字段合并。如果这个字段是一个标量值，该处理器会将其转换为数组字段。

例如如下的文档：

[source,js]
--------------------------------------------------
{
  "foo.bar" : "value2",
  "foo" : {
    "bar" : "value1"
  }
}
--------------------------------------------------
// NOTCONSOLE

将会被处理器 `dot_expander` 转换为:

[source,js]
--------------------------------------------------
{
  "foo" : {
    "bar" : ["value1", "value2"]
  }
}
--------------------------------------------------
// NOTCONSOLE

如果任何一个叶子字段之外的字段和将被处理器解析出来的字段同名，则必须先将其改名。

考虑如下文档：

[source,js]
--------------------------------------------------
{
  "foo": "value1",
  "foo.bar": "value2"
}
--------------------------------------------------
// NOTCONSOLE

其中的 `foo` 字段需要在处理器 `dot_expander` 应用之前先改名。因此为了顺利的将 `foo.bar` 字段扩展为 `foo` 下的 `bar` 字段，需要使用如下的管道：

[source,js]
--------------------------------------------------
{
  "processors" : [
    {
      "rename" : {
        "field" : "foo",
        "target_field" : "foo.bar""
      }
    },
    {
      "dot_expander": {
        "field": "foo.bar"
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

这样做的原因是因为 Ingest 并不知道如何自动的将一个标量字段转换为一个对象字段。

[[fail-processor]]
=== 失败处理器
该处理器主要是抛出异常。在预期管道可能会失败的场景非常有用，且可以返回一个具体的消息给请求方。

[[fail-options]]
.失败处理器选项
[options="header"]
|======
| 名称       | 必须      | 默认值   | 描述
| `message`  | 是        | -        | 处理器抛出的异常信息。支持<<accessing-template-fields, 模板片段>>。
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "fail": {
    "if" : "ctx.tags.contains('production') != true",
    "message": "The production tag is not present, found tags: {{tags}}"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[foreach-processor]]
=== 遍历处理器

遍历一个未知长度的数组。

所有的处理器可以处理素组中的每个元素，但是当数组中所有的元素都需要按照相同的方式处理的场景，为每个元素定义一个处理器将会变得笨重也很奇怪，因为数组元素的数量可能是未知的。这就是 `foreach` 遍历处理器存在的原因。通过指定包含数组元素的字段，并在处理器中指定如何处理每个元素，数组字段可以很容易被预处理。 

遍历处理器将会遍历数组中的每个元素内容并将其放入到 ingest 元数据字段 `_ingest._value` 中。注意如果一个处理器在遍历处理器之前已经使用了 `_ingest._value` 字段，这样该值将不能在遍历处理器中使用。遍历处理器会复原原始值，这个值可以在遍历处理器之后的处理器中正常使用。

注意，文档中的其它任何字段是可以被其它处理器访问和修改的，这个处理器仅仅只是将当前数组中的元素放到 ingest 元数据 `_ingest._value` 中作为一个可读属性。因此，其可能会被预处理。

如果遍历处理器处理数组中的元素失败了，且没有指定 `on_failure` 处理器，当前执行将会退出且不会对数组做任何操作。

[[foreach-options]]
.遍历处理器选项
[options="header"]
|======
| 名称             | 必须      | 默认值   | 描述
| `field`          | 是        | -        | 数组字段。
| `processor`      | 是        | -        | 处理器该字段的处理器。
| `ignore_missing` | 否        | 否       | 如果为 `true` 且 `field` 不存在或者为 `null` ，则处理器将会退出且不会对文档做任何修改。 
include::ingest-node-common-processor.asciidoc[]
|======

假设有如下文档：

[source,js]
--------------------------------------------------
{
  "values" : ["foo", "bar", "baz"]
}
--------------------------------------------------
// NOTCONSOLE

当如下的 `foreach` 遍历处理器操作该文档时：

[source,js]
--------------------------------------------------
{
  "foreach" : {
    "field" : "values",
    "processor" : {
      "uppercase" : {
        "field" : "_ingest._value"
      }
    }
  }
}
--------------------------------------------------
// NOTCONSOLE

文档将会被处理为：

[source,js]
--------------------------------------------------
{
  "values" : ["FOO", "BAR", "BAZ"]
}
--------------------------------------------------
// NOTCONSOLE

我们来看看另外一个例子：

[source,js]
--------------------------------------------------
{
  "persons" : [
    {
      "id" : "1",
      "name" : "John Doe"
    },
    {
      "id" : "2",
      "name" : "Jane Doe"
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

这个例子中， `id` 字段需要被删除，因此使用如下的遍历处理器：

[source,js]
--------------------------------------------------
{
  "foreach" : {
    "field" : "persons",
    "processor" : {
      "remove" : {
        "field" : "_ingest._value.id"
      }
    }
  }
}
--------------------------------------------------
// NOTCONSOLE

处理之后的结果如下：

[source,js]
--------------------------------------------------
{
  "persons" : [
    {
      "name" : "John Doe"
    },
    {
      "name" : "Jane Doe"
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

包装过的处理器可以包含失败处理器 `on_failure` 的定义。例如， 可能并不是每个 person 对象都包含 `id` 。为了不使整个 index 请求失败，你可以使用一个 `on_failure` 语句块将对应的文档发送到 'failure_index' 索引中便于后续分析：

[source,js]
--------------------------------------------------
{
  "foreach" : {
    "field" : "persons",
    "processor" : {
      "remove" : {
        "field" : "_value.id",
        "on_failure" : [
          {
            "set" : {
              "field", "_index",
              "value", "failure_index"
            }
          }
        ]
      }
    }
  }
}
--------------------------------------------------
// NOTCONSOLE

在这个例子中，如果 `remove` 处理器失败了，那么数组中已经处理过的元素将会被更新。

可以参考另外一个更高级一点的例子{plugins}/ingest-attachment-with-arrays.html[附加处理器文档].



[[grok-processor]]
=== Grok 处理器

该处理器从文档的单个文本字段中提取结构化字段。你可以选择从某个字段中提取匹配的字段，以及定义相应的 grok 匹配模式。Grok 模式和正则表达式类似，支持预定义一些表达式并重复利用。 

这个工具非常适合用于 syslog 日志、apache 以及其他 web 服务相关的日志、mysql 日志等。总的来说，除了机器随机产生的任何人为编写的格式都可以支持。该处理器提供很多https://github.com/elastic/elasticsearch/blob/{branch}/libs/grok/src/main/resources/patterns[可重用的模式]。

如果你需要关于构建日志匹配模式的帮助信息，可以利用{kibana-ref}/xpack-grokdebugger.html[Grok 调试器]工具协助。Grok 调试器是一个 {xpack} 基础许可证（Basic License）下面的功能，因此是 *免费使用* 的。Grok 构造器 <http://grokconstructor.appspot.com/> 也是非常有用的功能。

[[grok-basics]]
==== Grok 基础

Grok 是基于正则表达式的，因此所有的正则表达式在 grok 中都是支持的。正则表达式库是 Oniguruma，可以在 https://github.com/kkos/oniguruma/blob/master/doc/RE[Onigiruma 文档]上查看详细的语法。

Grok 处理器利用正则表达式预定义一些模式，然后将他们组合起来组成更复杂的模式来匹配对应的字段。

重用 grok 模式的语法有如下三种格式： `%{SYNTAX:SEMANTIC}` 、 `%{SYNTAX}` 、 `%{SYNTAX:SEMANTIC:TYPE}` 。

`SYNTAX` 是用来匹配对应文本的模式的名称。例如 `3.44` 会被 `NUMBER` 模式匹配， `55.3.244.1` 会被 `IP` 模式匹配。 `NUMBER` 和 `IP` 都属于 grok 提供的默认模式。

The `SEMANTIC` is the identifier you give to the piece of text being matched. For example, `3.44` could be the
duration of an event, so you could call it simply `duration`. Further, a string `55.3.244.1` might identify
the `client` making a request.

The `TYPE` is the type you wish to cast your named field. `int` and `float` are currently the only types supported for coercion.

For example, you might want to match the following text:

[source,txt]
--------------------------------------------------
3.44 55.3.244.1
--------------------------------------------------

You may know that the message in the example is a number followed by an IP address. You can match this text by using the following
Grok expression.

[source,txt]
--------------------------------------------------
%{NUMBER:duration} %{IP:client}
--------------------------------------------------

[[using-grok]]
==== Using the Grok Processor in a Pipeline

[[grok-options]]
.Grok Options
[options="header"]
|======
| Name                   | Required  | Default             | Description
| `field`                | yes       | -                   | The field to use for grok expression parsing
| `patterns`             | yes       | -                   | An ordered list of grok expression to match and extract named captures with. Returns on the first expression in the list that matches.
| `pattern_definitions`  | no        | -                   | A map of pattern-name and pattern tuples defining custom patterns to be used by the current processor. Patterns matching existing names will override the pre-existing definition.
| `trace_match`          | no        | false               | when true, `_ingest._grok_match_index` will be inserted into your matched document's metadata with the index into the pattern found in `patterns` that matched.
| `ignore_missing`       | no        | false               | If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

Here is an example of using the provided patterns to extract out and name structured fields from a string field in
a document.

[source,js]
--------------------------------------------------
{
  "message": "55.3.244.1 GET /index.html 15824 0.043"
}
--------------------------------------------------
// NOTCONSOLE

The pattern for this could be:

[source,txt]
--------------------------------------------------
%{IP:client} %{WORD:method} %{URIPATHPARAM:request} %{NUMBER:bytes} %{NUMBER:duration}
--------------------------------------------------

Here is an example pipeline for processing the above document by using Grok:

[source,js]
--------------------------------------------------
{
  "description" : "...",
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["%{IP:client} %{WORD:method} %{URIPATHPARAM:request} %{NUMBER:bytes} %{NUMBER:duration}"]
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

This pipeline will insert these named captures as new fields within the document, like so:

[source,js]
--------------------------------------------------
{
  "message": "55.3.244.1 GET /index.html 15824 0.043",
  "client": "55.3.244.1",
  "method": "GET",
  "request": "/index.html",
  "bytes": 15824,
  "duration": "0.043"
}
--------------------------------------------------
// NOTCONSOLE

[[custom-patterns]]
==== Custom Patterns

The Grok processor comes pre-packaged with a base set of pattern. These patterns may not always have
what you are looking for. Pattern have a very basic format. Each entry describes has a name and the pattern itself.

You can add your own patterns to a processor definition under the `pattern_definitions` option.
Here is an example of a pipeline specifying custom pattern definitions:

[source,js]
--------------------------------------------------
{
  "description" : "...",
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["my %{FAVORITE_DOG:dog} is colored %{RGB:color}"],
        "pattern_definitions" : {
          "FAVORITE_DOG" : "beagle",
          "RGB" : "RED|GREEN|BLUE"
        }
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE

[[trace-match]]
==== Providing Multiple Match Patterns

Sometimes one pattern is not enough to capture the potential structure of a field. Let's assume we
want to match all messages that contain your favorite pet breeds of either cats or dogs. One way to accomplish
this is to provide two distinct patterns that can be matched, instead of one really complicated expression capturing
the same `or` behavior.

Here is an example of such a configuration executed against the simulate API:

[source,js]
--------------------------------------------------
POST _ingest/pipeline/_simulate
{
  "pipeline": {
  "description" : "parse multiple patterns",
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["%{FAVORITE_DOG:pet}", "%{FAVORITE_CAT:pet}"],
        "pattern_definitions" : {
          "FAVORITE_DOG" : "beagle",
          "FAVORITE_CAT" : "burmese"
        }
      }
    }
  ]
},
"docs":[
  {
    "_source": {
      "message": "I love burmese cats!"
    }
  }
  ]
}
--------------------------------------------------
// CONSOLE

response:

[source,js]
--------------------------------------------------
{
  "docs": [
    {
      "doc": {
        "_type": "_type",
        "_index": "_index",
        "_id": "_id",
        "_source": {
          "message": "I love burmese cats!",
          "pet": "burmese"
        },
        "_ingest": {
          "timestamp": "2016-11-08T19:43:03.850+0000"
        }
      }
    }
  ]
}
--------------------------------------------------
// TESTRESPONSE[s/2016-11-08T19:43:03.850\+0000/$body.docs.0.doc._ingest.timestamp/]

Both patterns will set the field `pet` with the appropriate match, but what if we want to trace which of our
patterns matched and populated our fields? We can do this with the `trace_match` parameter. Here is the output of
that same pipeline, but with `"trace_match": true` configured:

////
Hidden setup for example:
[source,js]
--------------------------------------------------
POST _ingest/pipeline/_simulate
{
  "pipeline": {
  "description" : "parse multiple patterns",
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["%{FAVORITE_DOG:pet}", "%{FAVORITE_CAT:pet}"],
        "trace_match": true,
        "pattern_definitions" : {
          "FAVORITE_DOG" : "beagle",
          "FAVORITE_CAT" : "burmese"
        }
      }
    }
  ]
},
"docs":[
  {
    "_source": {
      "message": "I love burmese cats!"
    }
  }
  ]
}
--------------------------------------------------
// CONSOLE
////

[source,js]
--------------------------------------------------
{
  "docs": [
    {
      "doc": {
        "_type": "_type",
        "_index": "_index",
        "_id": "_id",
        "_source": {
          "message": "I love burmese cats!",
          "pet": "burmese"
        },
        "_ingest": {
          "_grok_match_index": "1",
          "timestamp": "2016-11-08T19:43:03.850+0000"
        }
      }
    }
  ]
}
--------------------------------------------------
// TESTRESPONSE[s/2016-11-08T19:43:03.850\+0000/$body.docs.0.doc._ingest.timestamp/]

In the above response, you can see that the index of the pattern that matched was `"1"`. This is to say that it was the
second (index starts at zero) pattern in `patterns` to match.

This trace metadata enables debugging which of the patterns matched. This information is stored in the ingest
metadata and will not be indexed.

[[grok-processor-rest-get]]
==== Retrieving patterns from REST endpoint

The Grok Processor comes packaged with its own REST endpoint for retrieving which patterns the processor is packaged with.

[source,js]
--------------------------------------------------
GET _ingest/processor/grok
--------------------------------------------------
// CONSOLE

The above request will return a response body containing a key-value representation of the built-in patterns dictionary.

[source,js]
--------------------------------------------------
{
  "patterns" : {
    "BACULA_CAPACITY" : "%{INT}{1,3}(,%{INT}{3})*",
    "PATH" : "(?:%{UNIXPATH}|%{WINPATH})",
    ...
}
--------------------------------------------------
// NOTCONSOLE

This can be useful to reference as the built-in patterns change across versions.

[[grok-watchdog]]
==== Grok watchdog

Grok expressions that take too long to execute are interrupted and
the grok processor then fails with an exception. The grok
processor has a watchdog thread that determines when evaluation of
a grok expression takes too long and is controlled by the following
settings:

[[grok-watchdog-options]]
.Grok watchdog settings
[options="header"]
|======
| Name                                      | Default | Description
| `ingest.grok.watchdog.interval`           | 1s      | How often to check whether there are grok evaluations that take longer than the maximum allowed execution time.
| `ingest.grok.watchdog.max_execution_time` | 1s      | The maximum allowed execution of a grok expression evaluation.
|======

[[gsub-processor]]
=== Gsub Processor
Converts a string field by applying a regular expression and a replacement.
If the field is not a string, the processor will throw an exception.

[[gsub-options]]
.Gsub Options
[options="header"]
|======
| Name              | Required  | Default  | Description
| `field`           | yes       | -        | The field to apply the replacement to
| `pattern`         | yes       | -        | The pattern to be replaced
| `replacement`     | yes       | -        | The string to replace the matching patterns with
| `target_field`    | no        | `field`  | The field to assign the converted value to, by default `field` is updated in-place
| `ignore_missing`  | no        | `false`  | If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "gsub": {
    "field": "field1",
    "pattern": "\.",
    "replacement": "-"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[join-processor]]
=== Join Processor
Joins each element of an array into a single string using a separator character between each element.
Throws an error when the field is not an array.

[[join-options]]
.Join Options
[options="header"]
|======
| Name              | Required  | Default  | Description
| `field`           | yes       | -        | The field to be separated
| `separator`       | yes       | -        | The separator character
| `target_field`    | no        | `field`  | The field to assign the joined value to, by default `field` is updated in-place
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "join": {
    "field": "joined_array_field",
    "separator": "-"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[json-processor]]
=== JSON Processor
Converts a JSON string into a structured JSON object.

[[json-options]]
.Json Options
[options="header"]
|======
| Name           | Required  | Default  | Description
| `field`        | yes       | -        | The field to be parsed
| `target_field` | no        | `field`  | The field to insert the converted structured object into
| `add_to_root`  | no        | false    | Flag that forces the serialized json to be injected into the top level of the document. `target_field` must not be set when this option is chosen.
include::ingest-node-common-processor.asciidoc[]
|======

All JSON-supported types will be parsed (null, boolean, number, array, object, string).

Suppose you provide this configuration of the `json` processor:

[source,js]
--------------------------------------------------
{
  "json" : {
    "field" : "string_source",
    "target_field" : "json_target"
  }
}
--------------------------------------------------
// NOTCONSOLE

If the following document is processed:

[source,js]
--------------------------------------------------
{
  "string_source": "{\"foo\": 2000}"
}
--------------------------------------------------
// NOTCONSOLE

after the `json` processor operates on it, it will look like:

[source,js]
--------------------------------------------------
{
  "string_source": "{\"foo\": 2000}",
  "json_target": {
    "foo": 2000
  }
}
--------------------------------------------------
// NOTCONSOLE

If the following configuration is provided, omitting the optional `target_field` setting:
[source,js]
--------------------------------------------------
{
  "json" : {
    "field" : "source_and_target"
  }
}
--------------------------------------------------
// NOTCONSOLE

then after the `json` processor operates on this document:

[source,js]
--------------------------------------------------
{
  "source_and_target": "{\"foo\": 2000}"
}
--------------------------------------------------
// NOTCONSOLE

it will look like:

[source,js]
--------------------------------------------------
{
  "source_and_target": {
    "foo": 2000
  }
}
--------------------------------------------------
// NOTCONSOLE

This illustrates that, unless it is explicitly named in the processor configuration, the `target_field`
is the same field provided in the required `field` configuration.

[[kv-processor]]
=== KV Processor
This processor helps automatically parse messages (or specific event fields) which are of the foo=bar variety.

For example, if you have a log message which contains `ip=1.2.3.4 error=REFUSED`, you can parse those automatically by configuring:


[source,js]
--------------------------------------------------
{
  "kv": {
    "field": "message",
    "field_split": " ",
    "value_split": "="
  }
}
--------------------------------------------------
// NOTCONSOLE

[[kv-options]]
.Kv Options
[options="header"]
|======
| Name             | Required  | Default  | Description
| `field`          | yes       | -        | The field to be parsed
| `field_split`    | yes       | -        | Regex pattern to use for splitting key-value pairs
| `value_split`    | yes       | -        | Regex pattern to use for splitting the key from the value within a key-value pair
| `target_field`   | no        | `null`   | The field to insert the extracted keys into. Defaults to the root of the document
| `include_keys`   | no        | `null`   | List of keys to filter and insert into document. Defaults to including all keys
| `exclude_keys`   | no        | `null`   | List of keys to exclude from document
| `ignore_missing` | no        | `false`  | If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
| `prefix`         | no        | `null`   | Prefix to be added to extracted keys
| `trim_key`       | no        | `null`   | String of characters to trim from extracted keys
| `trim_value`     | no        | `null`   | String of characters to trim from extracted values
| `strip_brackets` | no        | `false`  | If `true` strip brackets `()`, `<>`, `[]` as well as quotes `'` and `"` from extracted values
include::ingest-node-common-processor.asciidoc[]
|======


[[lowercase-processor]]
=== Lowercase Processor
Converts a string to its lowercase equivalent.

[[lowercase-options]]
.Lowercase Options
[options="header"]
|======
| Name             | Required  | Default  | Description
| `field`          | yes       | -        | The field to make lowercase
| `target_field`   | no        | `field`  | The field to assign the converted value to, by default `field` is updated in-place
| `ignore_missing` | no        | `false`  | If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "lowercase": {
    "field": "foo"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[pipeline-processor]]
=== Pipeline Processor
Executes another pipeline.

[[pipeline-options]]
.Pipeline Options
[options="header"]
|======
| Name             | Required  | Default  | Description
| `name`           | yes       | -        | The name of the pipeline to execute
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "pipeline": {
    "name": "inner-pipeline"
  }
}
--------------------------------------------------
// NOTCONSOLE

An example of using this processor for nesting pipelines would be:

Define an inner pipeline:

[source,js]
--------------------------------------------------
PUT _ingest/pipeline/pipelineA
{
  "description" : "inner pipeline",
  "processors" : [
    {
      "set" : {
        "field": "inner_pipeline_set",
        "value": "inner"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE

Define another pipeline that uses the previously defined inner pipeline:

[source,js]
--------------------------------------------------
PUT _ingest/pipeline/pipelineB
{
  "description" : "outer pipeline",
  "processors" : [
    {
      "pipeline" : {
        "name": "pipelineA"
      }
    },
    {
      "set" : {
        "field": "outer_pipeline_set",
        "value": "outer"
      }
    }
  ]
}
--------------------------------------------------
// CONSOLE
// TEST[continued]

Now indexing a document while applying the outer pipeline will see the inner pipeline executed
from the outer pipeline:

[source,js]
--------------------------------------------------
PUT /myindex/_doc/1?pipeline=pipelineB
{
  "field": "value"
}
--------------------------------------------------
// CONSOLE
// TEST[continued]

Response from the index request:

[source,js]
--------------------------------------------------
{
  "_index": "myindex",
  "_type": "_doc",
  "_id": "1",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1,
}
--------------------------------------------------
// TESTRESPONSE

Indexed document:

[source,js]
--------------------------------------------------
{
  "field": "value",
  "inner_pipeline_set": "inner",
  "outer_pipeline_set": "outer"
}
--------------------------------------------------
// NOTCONSOLE

[[remove-processor]]
=== Remove Processor
Removes existing fields. If one field doesn't exist, an exception will be thrown.

[[remove-options]]
.Remove Options
[options="header"]
|======
| Name             | Required  | Default  | Description
| `field`          | yes       | -        | Fields to be removed. Supports <<accessing-template-fields,template snippets>>.
| `ignore_missing` | no        | `false`  | If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

Here is an example to remove a single field:

[source,js]
--------------------------------------------------
{
  "remove": {
    "field": "user_agent"
  }
}
--------------------------------------------------
// NOTCONSOLE

To remove multiple fields, you can use the following query:

[source,js]
--------------------------------------------------
{
  "remove": {
    "field": ["user_agent", "url"]
  }
}
--------------------------------------------------
// NOTCONSOLE

[[rename-processor]]
=== Rename Processor
Renames an existing field. If the field doesn't exist or the new name is already used, an exception will be thrown.

[[rename-options]]
.Rename Options
[options="header"]
|======
| Name              | Required  | Default  | Description
| `field`           | yes       | -        | The field to be renamed. Supports <<accessing-template-fields,template snippets>>.
| `target_field`    | yes       | -        | The new name of the field. Supports <<accessing-template-fields,template snippets>>.
| `ignore_missing`  | no        | `false`  | If `true` and `field` does not exist, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "rename": {
    "field": "provider",
    "target_field": "cloud.provider"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[script-processor]]
=== Script Processor

Allows inline and stored scripts to be executed within ingest pipelines.

See <<modules-scripting-using, How to use scripts>> to learn more about writing scripts. The Script Processor
leverages caching of compiled scripts for improved performance. Since the
script specified within the processor is potentially re-compiled per document, it is important
to understand how script caching works. To learn more about
caching see <<modules-scripting-using-caching, Script Caching>>.

[[script-options]]
.Script Options
[options="header"]
|======
| Name                   | Required  | Default    | Description
| `lang`                 | no        | "painless" | The scripting language
| `id`                   | no        | -          | The stored script id to refer to
| `source`               | no        | -          | An inline script to be executed
| `params`               | no        | -          | Script Parameters
include::ingest-node-common-processor.asciidoc[]
|======

One of `id` or `source` options must be provided in order to properly reference a script to execute.

You can access the current ingest document from within the script context by using the `ctx` variable.

The following example sets a new field called `field_a_plus_b_times_c` to be the sum of two existing
numeric fields `field_a` and `field_b` multiplied by the parameter param_c:

[source,js]
--------------------------------------------------
{
  "script": {
    "lang": "painless",
    "source": "ctx.field_a_plus_b_times_c = (ctx.field_a + ctx.field_b) * params.param_c",
    "params": {
      "param_c": 10
    }
  }
}
--------------------------------------------------
// NOTCONSOLE

It is possible to use the Script Processor to manipulate document metadata like `_index` and `_type` during
ingestion. Here is an example of an Ingest Pipeline that renames the index and type to `my_index` no matter what
was provided in the original index request:

[source,js]
--------------------------------------------------
PUT _ingest/pipeline/my_index
{
    "description": "use index:my_index and type:_doc",
    "processors": [
      {
        "script": {
          "source": """
            ctx._index = 'my_index';
            ctx._type = '_doc';
          """
        }
      }
    ]
}
--------------------------------------------------
// CONSOLE

Using the above pipeline, we can attempt to index a document into the `any_index` index.

[source,js]
--------------------------------------------------
PUT any_index/_doc/1?pipeline=my_index
{
  "message": "text"
}
--------------------------------------------------
// CONSOLE
// TEST[continued]

The response from the above index request:

[source,js]
--------------------------------------------------
{
  "_index": "my_index",
  "_type": "_doc",
  "_id": "1",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1,
}
--------------------------------------------------
// TESTRESPONSE

In the above response, you can see that our document was actually indexed into `my_index` instead of
`any_index`. This type of manipulation is often convenient in pipelines that have various branches of transformation,
and depending on the progress made, indexed into different indices.

[[set-processor]]
=== Set Processor
Sets one field and associates it with the specified value. If the field already exists,
its value will be replaced with the provided one.

[[set-options]]
.Set Options
[options="header"]
|======
| Name       | Required  | Default  | Description
| `field` | yes       | -        | The field to insert, upsert, or update. Supports <<accessing-template-fields,template snippets>>.
| `value` | yes       | -        | The value to be set for the field. Supports <<accessing-template-fields,template snippets>>.
| `override` | no        | true     | If processor will update fields with pre-existing non-null-valued field. When set to `false`, such fields will not be touched.
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "set": {
    "field": "host.os.name",
    "value": "{{os}}"
  }
}
--------------------------------------------------
// NOTCONSOLE


[[ingest-node-set-security-user-processor]]
=== Set Security User Processor
Sets user-related details (such as `username`,  `roles`, `email`, `full_name`
and `metadata` ) from the current
authenticated user to the current document by pre-processing the ingest.

IMPORTANT: Requires an authenticated user for the index request.

[[set-security-user-options]]
.Set Security User Options
[options="header"]
|======
| Name          | Required  | Default                                                   | Description
| `field`       | yes       | -                                                         | The field to store the user information into.
| `properties`  | no        | [`username`, `roles`, `email`, `full_name`, `metadata`]   | Controls what user related properties are added to the `field`.
include::ingest-node-common-processor.asciidoc[]
|======

The following example adds all user details for the current authenticated user
to the `user` field for all documents that are processed by this pipeline:

[source,js]
--------------------------------------------------
{
  "processors" : [
    {
      "set_security_user": {
        "field": "user"
      }
    }
  ]
}
--------------------------------------------------
// NOTCONSOLE


[[split-processor]]
=== Split Processor
Splits a field into an array using a separator character. Only works on string fields.

[[split-options]]
.Split Options
[options="header"]
|======
| Name              | Required  | Default  | Description
| `field`           | yes       | -        | The field to split
| `separator`       | yes       | -        | A regex which matches the separator, eg `,` or `\s+`
| `target_field`    | no        | `field`  | The field to assign the split value to, by default `field` is updated in-place
| `ignore_missing`  | no        | `false`  | If `true` and `field` does not exist, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "split": {
    "field": "my_field",
    "separator": "\\s+" <1>
  }
}
--------------------------------------------------
// NOTCONSOLE
<1> Treat all consecutive whitespace characters as a single separator

[[sort-processor]]
=== Sort Processor
Sorts the elements of an array ascending or descending.  Homogeneous arrays of numbers will be sorted
numerically, while arrays of strings or heterogeneous arrays of strings + numbers will be sorted lexicographically.
Throws an error when the field is not an array.

[[sort-options]]
.Sort Options
[options="header"]
|======
| Name              | Required  | Default  | Description
| `field`           | yes       | -        | The field to be sorted
| `order`           | no        | `"asc"`  | The sort order to use. Accepts `"asc"` or `"desc"`.
| `target_field`    | no        | `field`  | The field to assign the sorted value to, by default `field` is updated in-place
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "sort": {
    "field": "array_field_to_sort",
    "order": "desc"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[trim-processor]]
=== Trim Processor
Trims whitespace from field.

NOTE: This only works on leading and trailing whitespace.

[[trim-options]]
.Trim Options
[options="header"]
|======
| Name              | Required  | Default  | Description
| `field`           | yes       | -        | The string-valued field to trim whitespace from
| `target_field`    | no        | `field`  | The field to assign the trimmed value to, by default `field` is updated in-place
| `ignore_missing`  | no        | `false`  | If `true` and `field` does not exist, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "trim": {
    "field": "foo"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[uppercase-processor]]
=== Uppercase Processor
Converts a string to its uppercase equivalent.

[[uppercase-options]]
.Uppercase Options
[options="header"]
|======
| Name             | Required  | Default  | Description
| `field`          | yes       | -        | The field to make uppercase
| `target_field`   | no        | `field`  | The field to assign the converted value to, by default `field` is updated in-place
| `ignore_missing` | no        | `false`  | If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "uppercase": {
    "field": "foo"
  }
}
--------------------------------------------------
// NOTCONSOLE

[[urldecode-processor]]
=== URL Decode Processor
URL-decodes a string

[[urldecode-options]]
.URL Decode Options
[options="header"]
|======
| Name             | Required  | Default  | Description
| `field`          | yes       | -        | The field to decode
| `target_field`   | no        | `field`  | The field to assign the converted value to, by default `field` is updated in-place
| `ignore_missing` | no        | `false`  | If `true` and `field` does not exist or is `null`, the processor quietly exits without modifying the document
include::ingest-node-common-processor.asciidoc[]
|======

[source,js]
--------------------------------------------------
{
  "urldecode": {
    "field": "my_url_to_decode"
  }
}
--------------------------------------------------
o/ NOTCONSOLE
