[[shard-allocation-filtering]]
=== 分片分配过滤

通过分片分配过滤，您可以指定允许哪些节点承载特定索引的分片。

NOTE: 下面介绍的每个索引的分片分配过滤器与 <<shards-allocation>> 中介绍的集群维度的分配过滤器一起工作。



在启动时可以为每个节点配置任意的元数据属性。例如，可以向下面这样为节点配置 'rack' 和  'size' 属性：


[source,sh]
------------------------
bin/elasticsearch -Enode.attr.rack=rack1 -Enode.attr.size=big  <1>
------------------------

<1> 这些属性设置也可以在配置文件 `elasticsearch.yml` 中指定。

这些元数据属性可以同 
`index.routing.allocation.*` 一起使用，从而将一个索引分配到一组指定的节点上。  例如我们可以像下面这样，将索引 `test` 迁移至 `big` 或
`medium` 节点上:


[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.include.size": "big,medium"
}
------------------------
// CONSOLE
// TEST[s/^/PUT test\n/]

或者，我们可以通过 `exclude` 规则将索引 `test` 从 `small` 节点移出：

[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.exclude.size": "small"
}
------------------------
// CONSOLE
// TEST[s/^/PUT test\n/]

可以指定多条规则，在这种情况下，分片分配时必须满足所有的条件。例如，我们可以把索引 `test` 迁移至  `rack1`  上的 `big` 节点。

[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.include.size": "big",
  "index.routing.allocation.include.rack": "rack1"
}
------------------------
// CONSOLE
// TEST[s/^/PUT test\n/]

NOTE: 如果某些条件无法被满足，则分片不会被迁移。

下列设置是 _动态的_ ，允许将存活的索引从一组节点迁移到另一组节点：

`index.routing.allocation.include.{attribute}`::

    Assign the index to a node whose `{attribute}` has at least one of the
    comma-separated values.
    将索引分配至某些节点， 该节点的 `{attribute}` 中至少包含逗号分隔值中的一个值。

`index.routing.allocation.require.{attribute}`::

    将索引分配至某些节点， 该节点的 `{attribute}` 中包含逗号分隔值中的 _所有值_ 。

`index.routing.allocation.exclude.{attribute}`::

    将索引分配至某些节点， 该节点的 `{attribute}` 中不包含逗号分隔值中的 _任何值_。

下列特殊属性也是被支持的:

[horizontal]
`_name`::       按节点名字匹配节点
`_host_ip`::    按 host IP 地址匹配节点（与主机名关联的 IP ）
`_publish_ip`:: 按 publish IP 地址匹配节点
`_ip`::         按 `_host_ip` 或 `_publish_ip` 匹配节点
`_host`::       按主机名匹配节点

所有属性值都可以用通配符指定, 例如:

[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.include._ip": "192.168.2.*"
}
------------------------
// CONSOLE
// TEST[skip:indexes don't assign]
