
[[index-modules]]
= 索引模块

[partintro]
--

索引模块是为每个索引创建的模块，控制与索引相关的各个方面。

[float]
[[index-modules-settings]]
== 索引设置

索引级别的设置是针对每个索引的设置。设置可以是：

_静态设置_::

它们只能在索引创建时设置或对一个<<indices-open-close,已关闭索引>>设置。

_动态设置_::

它们可以在一个存活的索引上通过<<indices-update-settings,更新索引设置>>的接口动态修改。

WARNING: 修改已关闭索引的静态或动态索引设置可能会导致错误的设置，在不删除或不重建索引的情况下无法纠正这些设置。

[float]
=== 静态索引设置

以下是与任何特定索引模块无关的所有 _静态_ 索引设置的列表：

`index.number_of_shards`::

    一个索引应具有的主分片个数。默认是5。这个设置只能在索引创建时设定。在已关闭索引上是不能被修改的。注意：一个索引最多可具有的分片数被限制在 `1024` 。这是一种安全方面的限制，防止因偶然创建索引时的资源分配，影响集群的稳定性。可以通过在集群的每个节点上指定 `export ES_JAVA_OPTS="-Des.index.max_number_of_shards=128"` 的系统参数来修改这一限制。

`index.shard.check_on_startup`::
+
--
是否需要在打开分片前检测其是否已损坏。当检测到损坏时，分片将禁止被打开。选项：

`false`::

    (默认值) 打开分片时不需要检测其是否已损坏。

`checksum`::

    检测是否有物理损坏。

`true`::

    检测是否有物理或逻辑损坏。这将消耗更多的CPU和内存使用率。

`fix`::

    效果同 `false` 。 此选项已弃用，将在7.0中完全删除。

WARNING: 仅限专家用户使用。检测大数据量索引的分片将耗费大量时间。
--      

[[index-codec]] `index.codec`::

    +默认值+ 是使用LZ4压缩算法压缩存储的数据, 但也可以设置为 +best_compression+
    ，这样将使用 https://en.wikipedia.org/wiki/DEFLATE[DEFLATE] 压缩算法以获取更高的压缩比, 以降低存储字段的速率为代价。如果你在更新压缩类型，新的压缩类型将在段合并后生效。段合并可通过<<indices-forcemerge,强制合并>>来强制执行。

[[routing-partition-size]] `index.routing_partition_size`::

    一个自定义的 <<mapping-routing-field,路由>> 值可映射到的分片数。默认值是1，只能在索引创建时被设置。该值必须小于 `index.number_of_shards` ，除非 `index.number_of_shards` 的值也是1。有关如何使用此设置的更多详细信息，请参阅
     <<routing-index-partition, 路由至索引分区>> 。

[float]
[[dynamic-index-settings]]
=== 动态索引设置


以下是与任何特定索引模块无关的所有 _动态_ 索引设置的列表：

`index.number_of_replicas`::

    每个主分片拥有的副本数。 默认值是1。

`index.auto_expand_replicas`::

    根据群集中的数据节点数自动扩展副本数。
    可设置为以破折号分隔的上下限 (例如 `0-5`) 或使用 `all`
    作为上限 (例如 `0-all`)。 默认为 `false` (也就是 禁用)。
    请注意，自动扩展的副本数量不会考虑任何其他分配规则，比如 <<allocation-awareness,分片分配的awareness>>，
    <<shard-allocation-filtering,分片分配的过滤规则>> 或者 <<allocation-total-shards,每个节点上的分片数>>，当可应用的分片分配规则阻止了所有副本的分配时，这可能导致群集运行状态变为“黄色”。

`index.refresh_interval`::

    多久执行一次刷新操作，它会使得索引最近的更改对搜索可见。默认值是 `1s`。 可以设为 `-1`  来关闭刷新。

`index.max_result_window`::

    搜索该索引时， `from + size` 可使用的最大值。 默认值是
    `10000` 。 搜索请求使用的堆内存和时间同
    `from + size` 成正比，该设置限制了内存使用量。 可参考    <<search-request-scroll,Scroll>> 或 <<search-request-search-after,Search After>> 以获得更有效的替代方案。

`index.max_inner_result_window`::

    搜索该索引时，inner hits查询和top hits聚合可使用的 `from + size` 最大值。默认是
    `100` 。 Inner hits查询和top hits聚合使用的堆内存和时间同
    `from + size` 成正比，该设置限制了内存使用量。 

`index.max_rescore_window`::

    搜索该索引时，`rescore` 请求可使用的 `window_size`  最大值。
    默认使用 `index.max_result_window` 设定的值， 其默认值为 `10000`。 搜索请求使用的堆内存和时间同
    `max(window_size, from + size)` 成正比，该设置限制了内存使用量。 

`index.max_docvalue_fields_search`::

    一次查询允许使用的 `docvalue_fields` 数量的最大值。默认值是 `100` 。 Doc-value fields 的成本很高，因为它们可引发逐文档逐字段的遍历搜索。

`index.max_script_fields`::

    一次查询允许使用的 `script_fields` 数量的最大值。默认值是 `32` 。

`index.max_ngram_diff`::

    NGramTokenizer和NGramTokenFilter的min_gram和max_gram之间允许的最大差值。
    默认值是 `1` 。

`index.max_shingle_diff`::

    ShingleTokenFilter的max_shingle_size和min_shingle_size之间允许的最大差值。
    默认值是 `3` 。

`index.blocks.read_only`::

    设为 `true` 使得该索引和索引的元数据只读, 设为 `false` 以允许写入和元数据更改。

`index.blocks.read_only_allow_delete`::

    与 `index.blocks.read_only` 意义相同，但允许删除索引以释放资源。

`index.blocks.read`::

    设为 `true` 以禁用对该索引的读取操作。

`index.blocks.write`::

    设为 `true` 以禁用对该索引的写入操作。 不同于 `read_only`，
    该设置不会影响元数据写入。 例如, 您可以关闭一个设有 `write` 
    阻塞的索引，但无法关闭一个设有 `read_only` 阻塞的索引。

`index.blocks.metadata`::

    设为 `true` 以禁用索引元数据的读取和写入。

`index.max_refresh_listeners`::

    该index的每个shard上刷新监听者的最大数量。这些监听者用于实现 <<docs-refresh,`refresh=wait_for`>>。

 `index.highlight.max_analyzed_offset`::

     对一个高亮请求，可分析的最大字节数。
     这个设置仅对未创建偏移和词条向量索引的文本上的高亮请求生效。默认情况下该设置在6.x中未设置，默认值是 `-1` 。

 `index.max_terms_count`::

    词条查询可使用的最大词条数量。
    默认值是 `65536`。

 `index.routing.allocation.enable`::

    控制该索引的分片分配。 可以设置为:
    * `all` (默认值) - 允许分配所有的分片。
    * `primaries` - 只允许分配主分片。
    * `new_primaries` - 只允许分配新创建的主分片。
    * `none` - 不允许分配任何分片。

 `index.routing.rebalance.enable`::

    启用该索引的分片再均衡。 可以设置为:
    * `all` (default) - 允许再均衡所有的分片。
    * `primaries` - 只允许再均衡主分片。
    * `replicas` - 只允许再均衡副本分片。
    * `none` - 不允许再均衡任何分片。

 `index.gc_deletes`::

     仍可用于<<index-versioning,下一步版本化的操作>>的<<delete-versioning,已删除文档版本号>>的保留时间长度。
    默认值是 `60s`。

 `index.max_regex_length`::

    正则表达式查询的中可使用的正则表达式长度最大值。
    默认值是 `1000`。

  `index.default_pipeline`::

    该索引默认的 <<ingest,ingest节点>> 管道。如果默认管道已被设置但此管道不存在，写入请求会失败。 可通过 `pipeline` 参数覆盖默认值。 特殊的管道名称 `_none` 表示不运行任何ingest管道。

[float]
=== 其他索引模块的设置

索引模块中提供了其他索引设置：

<<analysis,分析>>::

    用于定义分析器，分词器，分词过滤器和字符过滤器的设置。

<<index-modules-allocation,索引分片分配>>::

    控制在何处、何时以及如何将碎片分配给节点。

<<index-modules-mapper,映射>>::

    启用或禁用索引的动态映射。

<<index-modules-merge,合并>>::

    控制后台的合并过程怎样合并分片。

<<index-modules-similarity,相似性>>::

    配置自定义相似性设置，从而自定义搜索结果的评分方式。

<<index-modules-slowlog,慢日志>>::

    控制慢查询和fetch请求怎样被记录至日志。

<<index-modules-store,存储>>::

    配置用于访问分片数据的文件系统类型。

<<index-modules-translog,事务日志>>::

    控制事务日志和后台刷新操作。

--

include::index-modules/analysis.asciidoc[]

include::index-modules/allocation.asciidoc[]

include::index-modules/mapper.asciidoc[]

include::index-modules/merge.asciidoc[]

include::index-modules/similarity.asciidoc[]

include::index-modules/slowlog.asciidoc[]

include::index-modules/store.asciidoc[]

include::index-modules/translog.asciidoc[]

include::index-modules/index-sorting.asciidoc[]
